plugins:
  house_ads_name:
    client: true
    default: ""

  house_ads_list_1_title:
    client: true
    default: "List #1"

  house_ads_list_1_url:
    client: true
    default: "/"

  house_ads_list_2_title:
    client: true
    default: "List #2"

  house_ads_list_2_url:
    client: true
    default: "/"

  house_ads_query_path_1:
    client: true
    default: ""

  house_ads_query_path_2:
    client: true
    default: ""

  house_ads_query_path_announcements:
    client: true
    default: ""

  house_ads_sidebar_max_topics:
    client: true
    default: 2
